content/2023/kickstart-2023-wrap-up: Blog post (very old draft)
AaltoSciComp/blog pull request #13
Opened 2023-11-20 19:27 UTC by rkdarst

- Draft post I found uncommitted in my working directory.  Did a bit
  of fix-up and PRing.
- Review: give it a good read and add more opinions to it.

2024-02-13 11:59 UTC, teemu-ruokolainen commented on content/2023/kickstart-2023-wrap-up.rst
> +scale.  Reading + livestream + videos is a good combination.
What is this "reading" referring to? The collab notes, sphinx material?

2024-02-13 12:00 UTC, teemu-ruokolainen commented on content/2023/kickstart-2023-wrap-up.rst
> +Repitition is good, but not when it's a sign that we can't stop
Typo: Repetition

2024-02-13 13:20 UTC, YuTian8328 commented on content/2023/kickstart-2023-wrap-up.rst
> +
Maybe shortly mention how the courses are evolving over years.

2024-02-13 13:22 UTC, ruokolt commented on content/2023/kickstart-2023-wrap-up.rst
> +Divide the course into two
The course was not divided so maybe this title should be "Should the course be divided into two?"

2024-02-13 13:22 UTC, teemu-ruokolainen requested changes
Looks good! A few small comments here and there.

2024-02-14 00:05 UTC, rkdarst commented
Various updates pushed.

2024-02-15 12:02 UTC, rkdarst commented on content/2024/kickstart-2023-wrap-up.rst
> +:date: 2024-02-13
```suggestion
:date: 2024-02-15
```

2024-02-15 12:03 UTC, merged