content/2023/rse-funding: Blog post on status of RSE funding
AaltoSciComp/blog pull request #5
Opened 2023-05-17 09:20 UTC by rkdarst

- Review: general overview is correct, phrasing + syntax check is
  good.

2024-02-13 13:26 UTC, rantahar requested changes

2024-02-13 13:26 UTC, rantahar commented on content/2023/rse-funding.rst
> +with Finance.  As for as external finders are concerned, our staff
```suggestion
with Finance.  As for as external funders are concerned, our staff
```

2024-02-19 09:53 UTC, rantahar approved these changes

2024-02-19 09:54 UTC, rantahar approved these changes

2024-02-20 11:15 UTC, rkdarst commented on content/2024/rse-funding.rst
> +:date: 2024-02-14
```suggestion
:date: 2024-02-21
```

2024-02-28 10:06 UTC, merged